INDEX=19
URL=https://delartemagazine.com/music/endzhel-vong-oshhushhayu-sebya-amerikancem-s-russkoj-dushoj/
ROBOT=autorisé
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru1/ru1-19.txt
HTML_DUMP=html_dump/ru1-19.html
TOTAL_WORDS=2832
TARGET_TOTAL=4
KWIC=csv/ru1-19.csv
