INDEX=6
URL=https://www.gotquestions.org/Russian/Russian-human-soul.html
ENCODING=indisponible
HTTP_CODE=404
TXT_DUMP=txt/original/ru1/ru1-6.txt
HTML_DUMP=html_dump/ru1-6.html
TOTAL_WORDS=697
TARGET_TOTAL=27
KWIC=csv/ru1-6.csv
