INDEX=22
URL=https://whitehall.spbstu.ru/
ROBOT=interdit
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru1/ru1-22.txt
HTML_DUMP=html_dump/ru1-22.html
TOTAL_WORDS=1719
TARGET_TOTAL=0
KWIC=csv/ru1-22.csv
