INDEX=10
URL=https://www.memoral.lv/ru/post/%D1%87%D1%82%D0%BE-%D1%82%D0%B0%D0%BA%D0%BE%D0%B5-%D0%B4%D1%83%D1%88%D0%B0
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru1/ru1-10.txt
HTML_DUMP=html_dump/ru1-10.html
TOTAL_WORDS=1029
TARGET_TOTAL=48
KWIC=csv/ru1-10.csv
