INDEX=28
URL=https://my.tretyakov.ru/app/masterpiece/51847
ROBOT=autorisé
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru1/ru1-28.txt
HTML_DUMP=html_dump/ru1-28.html
TOTAL_WORDS=529
TARGET_TOTAL=7
KWIC=csv/ru1-28.csv
