INDEX=5
URL=https://supernatural.fandom.com/ru/wiki/%D0%94%D1%83%D1%88%D0%B0
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru1/ru1-5.txt
HTML_DUMP=html_dump/ru1-5.html
TOTAL_WORDS=3008
TARGET_TOTAL=49
KWIC=csv/ru1-5.csv
