INDEX=18
URL=https://genius.com/Navernoe-poet-even-cute-yakor-and-derzko69-russian-soul-lyrics
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru1/ru1-18.txt
HTML_DUMP=html_dump/ru1-18.html
TOTAL_WORDS=1149
TARGET_TOTAL=20
KWIC=csv/ru1-18.csv
