INDEX=14
URL=https://www.tretyakovgallery.ru/exhibitions/o/russkaya-dusha-izbrannye-proizvedeniya-zhivopisi-iz-gosudarstvennoy-tretyakovskoy-galerei-i-tsifrovy/
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru1/ru1-14.txt
HTML_DUMP=html_dump/ru1-14.html
TOTAL_WORDS=29
TARGET_TOTAL=0
KWIC=csv/ru1-14.csv
