INDEX=23
URL=https://www.woman.ru/rest/bez-mechty-chelovek-prevrashaetsya-v-funkciyu-artem-mironov-o-svete-muzyke-i-vnutrennei-tochke-opory-id6718625/
ROBOT=autorisé
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru1/ru1-23.txt
HTML_DUMP=html_dump/ru1-23.html
TOTAL_WORDS=1381
TARGET_TOTAL=9
KWIC=csv/ru1-23.csv
