INDEX=17
URL=https://ru.wikipedia.org/wiki/%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B0%D1%8F_%D0%B4%D1%83%D1%88%D0%B0
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru1/ru1-17.txt
HTML_DUMP=html_dump/ru1-17.html
TOTAL_WORDS=2553
TARGET_TOTAL=139
KWIC=csv/ru1-17.csv
