INDEX=25
URL=https://www.innosocium.org/projects/4
ROBOT=autorisé
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru1/ru1-25.txt
HTML_DUMP=html_dump/ru1-25.html
TOTAL_WORDS=1401
TARGET_TOTAL=36
KWIC=csv/ru1-25.csv
