INDEX=12
URL=https://stihi.ru/2025/06/10/7341
ENCODING=windows-1251
HTTP_CODE=200
TXT_DUMP=txt/original/ru1/ru1-12.txt
HTML_DUMP=html_dump/ru1-12.html
TOTAL_WORDS=3528
TARGET_TOTAL=118
KWIC=csv/ru1-12.csv
