INDEX=30
URL=https://www.pravmir.ru/dushacheloveka/
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru1/ru1-30.txt
HTML_DUMP=html_dump/ru1-30.html
TOTAL_WORDS=4652
TARGET_TOTAL=134
KWIC=csv/ru1-30.csv
