INDEX=9
URL=https://jewish.ru/ru/traditions/articles/9217/
ROBOT=autorisé
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru1/ru1-9.txt
HTML_DUMP=html_dump/ru1-9.html
TOTAL_WORDS=1196
TARGET_TOTAL=37
KWIC=csv/ru1-9.csv
