INDEX=24
URL=https://mvdmedia.ru/publications/shield-and-sword/bylo-delo/dusha-otklikalas-na-krasotu-/
ROBOT=autorisé
ENCODING=indisponible
HTTP_CODE=405
TXT_DUMP=txt/original/ru1/ru1-24.txt
HTML_DUMP=html_dump/ru1-24.html
TOTAL_WORDS=1369
TARGET_TOTAL=2
KWIC=csv/ru1-24.csv
