INDEX=2
URL=https://ru.wiktionary.org/wiki/%D0%B4%D1%83%D1%88%D0%B0
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru1/ru1-2.txt
HTML_DUMP=html_dump/ru1-2.html
TOTAL_WORDS=7083
TARGET_TOTAL=621
KWIC=csv/ru1-2.csv
