INDEX=29
URL=https://www.gotquestions.org/Russian/Russian-human-spirit.html
ENCODING=indisponible
HTTP_CODE=404
TXT_DUMP=txt/original/ru2/ru2-29.txt
HTML_DUMP=html_dump/ru2-29.html
TOTAL_WORDS=615
TARGET_TOTAL=31
KWIC=csv/ru2-29.csv
