INDEX=2
URL=https://ru.wiktionary.org/wiki/%D0%B4%D1%83%D1%85
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru2/ru2-2.txt
HTML_DUMP=html_dump/ru2-2.html
TOTAL_WORDS=7833
TARGET_TOTAL=670
KWIC=csv/ru2-2.csv
