INDEX=13
URL=https://kluch.media/materials/my-dolgoe-ekho-drug-druga-kollektsiya-obrazov-v-fotoproekte-po-motivam-tvorchestva-roberta-rozhdestv/
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru2/ru2-13.txt
HTML_DUMP=html_dump/ru2-13.html
TOTAL_WORDS=3192
TARGET_TOTAL=1
KWIC=csv/ru2-13.csv
