INDEX=18
URL=https://vecherka-spb.ru/2025/12/18/v-svr-zayavili-chto-korruptsionnii-skandal-na-ukraine-vizval-padenie-moralnogo-dukha-vsu
ENCODING=indisponible
HTTP_CODE=200
TXT_DUMP=txt/original/ru2/ru2-18.txt
HTML_DUMP=html_dump/ru2-18.html
TOTAL_WORDS=1
TARGET_TOTAL=0
KWIC=csv/ru2-18.csv
