INDEX=19
URL=https://spbdnevnik.ru/news/2025-12-22/prodolzhayte-v-tom-zhe-dukhe-evgeniy-razumishkin-posetil-novogodnyuyu-pochtu-peterburgskogo-dnevnika
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru2/ru2-19.txt
HTML_DUMP=html_dump/ru2-19.html
TOTAL_WORDS=389
TARGET_TOTAL=3
KWIC=csv/ru2-19.csv
