INDEX="28"
URL="https://azbyka.ru/forum/threads/chto-takoe-dux.3377/"
ROBOT="autorisé"
ENCODING="utf-8"
HTTP_CODE="200"
TXT_DUMP="txt/original/ru2/ru2-28.txt"
HTML_DUMP=html_dump/ru2-28.html
TOTAL_WORDS=3620
TARGET_TOTAL=119
KWIC=csv/ru2-28.csv
