INDEX=22
URL=https://www.gazeta.ru/politics/news/2025/12/21/27466567.shtml
ENCODING=indisponible
HTTP_CODE=302
TXT_DUMP=txt/original/ru2/ru2-22.txt
HTML_DUMP=html_dump/ru2-22.html
TOTAL_WORDS=0
TARGET_TOTAL=0
KWIC=csv/ru2-22.csv
