INDEX="4"
URL="https://bigenc.ru/c/dukh-0ed059"
ROBOT="autorisé"
ENCODING="utf-8"
HTTP_CODE="200"
TXT_DUMP="txt/original/ru2/ru2-4.txt"
HTML_DUMP=html_dump/ru2-4.html
TOTAL_WORDS=1304
TARGET_TOTAL=45
KWIC=csv/ru2-4.csv
