INDEX="11"
URL="https://ugramegasport.ru/2025/12/20/sledzh-hokkej-igra-vdohnovlennaya-siloj-duha-i-volej-k-pobede/"
ROBOT="autorisé"
ENCODING="utf-8"
HTTP_CODE="200"
TXT_DUMP="txt/original/ru2/ru2-11.txt"
HTML_DUMP=html_dump/ru2-11.html
TOTAL_WORDS=740
TARGET_TOTAL=2
KWIC=csv/ru2-11.csv
