INDEX="12"
URL="https://cultura24.ru/news/22996/"
ROBOT="autorisé"
ENCODING="utf-8"
HTTP_CODE="200"
TXT_DUMP="txt/original/ru2/ru2-12.txt"
HTML_DUMP=html_dump/ru2-12.html
TOTAL_WORDS=386
TARGET_TOTAL=3
KWIC=csv/ru2-12.csv
