INDEX="21"
URL="https://mir24.tv/news/16656109/glavnoe-na-pole-komandnyj-duh.-komanda-mtrk-mir-debyutirovala-na-futbolnom-turnire-zhurnalistov-v-baku"
ROBOT="autorisé"
ENCODING="indisponible"
HTTP_CODE="403"
TXT_DUMP="txt/original/ru2/ru2-21.txt"
HTML_DUMP=html_dump/ru2-21.html
TOTAL_WORDS=28
TARGET_TOTAL=0
KWIC=csv/ru2-21.csv
