INDEX="5"
URL="https://azbyka.ru/duxh"
ROBOT="autorisé"
ENCODING="indisponible"
HTTP_CODE="404"
TXT_DUMP="txt/original/ru2/ru2-5.txt"
HTML_DUMP=html_dump/ru2-5.html
TOTAL_WORDS=15
TARGET_TOTAL=0
KWIC=csv/ru2-5.csv
