INDEX="7"
URL="https://dzen.ru/a/YSdQFQnD3xk2pM3u"
ROBOT="autorisé"
ENCODING="utf-8"
HTTP_CODE="200"
TXT_DUMP="txt/original/ru2/ru2-7.txt"
HTML_DUMP=html_dump/ru2-7.html
TOTAL_WORDS=0
TARGET_TOTAL=0
KWIC=csv/ru2-7.csv
