INDEX=16
URL=https://rplinevo.nso.ru/news/6559
ENCODING=indisponible
HTTP_CODE=403
TXT_DUMP=txt/original/ru2/ru2-16.txt
HTML_DUMP=html_dump/ru2-16.html
TOTAL_WORDS=4
TARGET_TOTAL=0
KWIC=csv/ru2-16.csv
