INDEX=30
URL=https://kontrudar.com/faq/duh-i-sushchnost
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru2/ru2-30.txt
HTML_DUMP=html_dump/ru2-30.html
TOTAL_WORDS=2390
TARGET_TOTAL=33
KWIC=csv/ru2-30.csv
