INDEX=20
URL=https://izvmor.ru/novosti/obshchestvo/v-saranske-nagradili-pobeditelej-konkursa-aleksandr-nevskij-slava-duh-i-imya-rossii/
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru2/ru2-20.txt
HTML_DUMP=html_dump/ru2-20.html
TOTAL_WORDS=897
TARGET_TOTAL=7
KWIC=csv/ru2-20.csv
