INDEX=9
URL=https://vc.ru/opinions/1672265-chto-takoe-duh-i-chto-takoe-dusha
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru2/ru2-9.txt
HTML_DUMP=html_dump/ru2-9.html
TOTAL_WORDS=467
TARGET_TOTAL=10
KWIC=csv/ru2-9.csv
