INDEX="14"
URL="https://kamensk-uralskiy.ru/news/novosti_administracii/28481-zdes-russkiy-duh-zdes-rusyu-pahnet.html"
ROBOT="autorisé"
ENCODING="utf-8"
HTTP_CODE="200"
TXT_DUMP="txt/original/ru2/ru2-14.txt"
HTML_DUMP=html_dump/ru2-14.html
TOTAL_WORDS=1652
TARGET_TOTAL=2
KWIC=csv/ru2-14.csv
