INDEX=15
URL=https://gazeta19.ru/news/kultura/multfilmy-volk-i-kon-i-rybak-i-vodnyy-dukh-prezentovali-v-khakasii/
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru2/ru2-15.txt
HTML_DUMP=html_dump/ru2-15.html
TOTAL_WORDS=721
TARGET_TOTAL=2
KWIC=csv/ru2-15.csv
