INDEX=23
URL=https://www.ogirk.ru/2025/12/17/strelba-iz-luka-zakaljaet-harakter-i-silu-duha/
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru2/ru2-23.txt
HTML_DUMP=html_dump/ru2-23.html
TOTAL_WORDS=943
TARGET_TOTAL=2
KWIC=csv/ru2-23.csv
