INDEX=1
URL=https://ru.wikipedia.org/wiki/%D0%94%D1%83%D1%85_(%D1%84%D0%B8%D0%BB%D0%BE%D1%81%D0%BE%D1%84%D0%B8%D1%8F)
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru2/ru2-1.txt
HTML_DUMP=html_dump/ru2-1.html
TOTAL_WORDS=1218
TARGET_TOTAL=84
KWIC=csv/ru2-1.csv
