INDEX=8
URL=https://tenchat.ru/media/1381468-v-chem-razlichiye-i-skhodstvo-dushi-i-dukha
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru2/ru2-8.txt
HTML_DUMP=html_dump/ru2-8.html
TOTAL_WORDS=856
TARGET_TOTAL=19
KWIC=csv/ru2-8.csv
