INDEX="10"
URL="https://www.b17.ru/article/chto-takoe-duh/"
ROBOT="autorisé"
ENCODING="windows-1251"
HTTP_CODE="200"
TXT_DUMP="txt/original/ru2/ru2-10.txt"
HTML_DUMP=html_dump/ru2-10.html
TOTAL_WORDS=10542
TARGET_TOTAL=295
KWIC=csv/ru2-10.csv
