INDEX=24
URL=https://globalcity.info/photo/22-12-2025/69822
ENCODING=utf-8
HTTP_CODE=200
TXT_DUMP=txt/original/ru2/ru2-24.txt
HTML_DUMP=html_dump/ru2-24.html
TOTAL_WORDS=1076
TARGET_TOTAL=3
KWIC=csv/ru2-24.csv
