# PROCESSED FILES CONFIG
SOURCE_DIR="txt/original"
PROCESSED_EXPORT_DIR="txt/processed"
# CSV CONFIG
CSV_EXPORT_PATH="ru_kwic.csv"
CSV_HEADERS="before4;before3;before2;before1;target;after1;after2;after3;after4"

# Define mapping
declare -A PATTERNS
# \p{L} matches any unicode character 
# (?<!\p{L}) no letter before the match
# (?!\p{L}) no letter after the match
PATTERNS["ru1"]="(?<!\p{L})душ(а|и|е|у|ой|ою|ами|ах)(?!\p{L})"
PATTERNS["ru2"]="(?<!\p{L})дух(а|у|ом|е|и|ов|ам|ами|ах)?(?!\p{L})"
