SOURCE_DIR="txt/original"
EXPORT_DIR="txt/processed"

# \p{L} matches any unicode character 
# (?<!\p{L}) no letter before the match
# (?!\p{L}) no letter after the match
# Define mapping
declare -A PATTERNS
PATTERNS["ru1"]="(?<!\p{L})душ(а|и|е|у|ой|ою|ами|ах)(?!\p{L})"
PATTERNS["ru2"]="(?<!\p{L})дух(а|у|ом|е|и|ов|ам|ами|ах)?(?!\p{L})"
