# Url converter config 
UTF_ENCODING_LINE="content-type: text/html; charset=utf-8"
# Raw patterns
declare -A RAW_PATTERNS
RAW_PATTERNS["ru1"]="душ(а|и|е|у|ой|ою|ами|ах)"
RAW_PATTERNS["ru2"]="дух(а|у|ом|е|и|ов|ам|ами|ах)?"
# PROCESSED FILES CONFIG
SOURCE_DIR="txt/original"
PROCESSED_EXPORT_DIR="txt/processed"
# CSV CONFIG
CSV_EXPORT_PATH="ru_kwic.csv"
# ! Before modifying headers or context window values, make sure to make them match
# For instance, here the headers shows 4 words of context after and before, hence the context window is 4
CSV_HEADERS="before4;before3;before2;before1;target;after1;after2;after3;after4" # This is the header of the CSV file
CONTEXT_WINDOW=4 # This is how many words of context we have in the CSV
declare -A CSV_PATTERNS
# \b means a word boundary
# So it extracts only the words we want, and does not take into account possible corresponding substrings
CSV_PATTERNS["ru1"]="\\b${RAW_PATTERNS["ru1"]}\\b"
CSV_PATTERNS["ru2"]="\\b${RAW_PATTERNS["ru2"]}\\b"
# Define mapping of the patterns
declare -A PATTERNS
# \p{L} matches any unicode character 
# (?<!\p{L}) no letter before the match
# (?!\p{L}) no letter after the match
PATTERNS["ru1"]="(?<!\p{L})${RAW_PATTERNS["ru1"]}(?!\p{L})"
PATTERNS["ru2"]="(?<!\p{L})${RAW_PATTERNS["ru2"]}(?!\p{L})"
# Metadata
METADATA_FOLDER="metadata"